---
title: "Coffee Drinking Habits and Working Lifestyle"
subtitle: "INFO 526 - Summer 2024 - Final Project"
author: 
  - name: "Vera Jackson"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "A data-driven analysis on how much coffee are people drinking, and what lifestyle conditions correlate with this?"
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
bibliography: references.bib
---

## Abstract

Add project abstract here.

## Introduction

Coffee is one of the most popular drinks in the world, and in the USA alone, 75% of the population has reported drinking coffee, with almost half of Americans drinking coffee daily (Loftfield, et al. 2016). There are many reasons why people drink coffee - for some it is a habit or part of their morning routine, some need the caffeine, and some just like the way it tastes. Studies have shown that demographic factors, such as gender and race, influence how much coffee someone drinks (Loftfield, et al. 2016). However, one's lifestyle and environment may also have a part to play in this.

The "Great American Coffee Taste Test" data set is compiled of survey results that were filled out by participants of a taste test, hosted by "world champion barista" James Hoffman and coffee company Cometeer. Cometeer sent 4 unlabelled coffees to over 4,000 customers that would participate in a live taste testing on YouTube while filling out the survey. The survey includes questions about coffee drinking habits, coffee preferences, individual taste test results for each of the 4 provides coffees, and individual demographics.

## Question: What are the correlations between coffee consumption and lifestyle?\*

### Introduction

To answer this question, we will be looking at the "Great American Coffee Taste Test" data set. .

The data has a wide range of questions, with 4,042 responses. Rather than looking at demographics such as gender and race, I was curious about how someone's lifestyle, primarily focused on one's working habits, impacts how much coffee they drink. For the purpose of this question, we will only be looking at the following variables, with the following options to answer in the survey:

-   `cups`:

    -   "`Less than 1`", "`1`", "`2`", "`3`", "`4`", "`More than 4`"

-   `employment_status`:

    -   "`Retired`", "`Employed full-time`", "`Employed part-time`", "`Homemaker`", "`Student`", "`Unemployed`"

-   `number_children`:

    -   "`None`", "`1`", "`2`", "`3`", "`More than 3`"

-   `wfh`:

    -   `"I primarily work in person", "I primarily work from home", "I do a mix of both"`

-   `age`:

    -   `"<18 years old", "18-24 years old", "25-34 years old", "35-44 years old", "45-54 years old", "55-64 years old", ">65 years old"`"

Removing any responses that did not respond to each of these questions, we are working with 3, 343 responses.

I chose this data set because I was curious about the demographics and preferences of coffee drinkers, both of customers of Cometeer and as a representation of the general North American population. My first question will look at coffee drinking habits (how many cups of coffee are drunken a day) and how they correlate with working and lifestyle situations (whether they work or not, if they work from home or not, and how many children they have). It could be interesting to further analyze that data with why they drink coffee (for the caffeine, or is it for the flavor?) or if that coffee is caffeinated or not, but I want to be careful of not introducing too many variables. Overall, my goal for the first question is to highlight a trend between coffee drinking and lifestyle that could be reflective of the general American population. As for my second question, I am taking a more "marketing" approach, as I will try to determine which type of coffee (in regards to strength, roast, and caffeine-level) is most popular among Cometeer customers, as this information could assist them with product development.

### Approach

### Analysis

### Discussion

## References
